arb-dir: assets/l10n
template-arb-file: intl_en.arb
output-localization-file: l10n.dart
output-class: L10n
preferred-supported-locales: ["en"]
# Workaround from https://github.com/flutter/flutter/issues/148333#issuecomment-2122333090
synthetic-package: false
output-dir: lib/l10n
nullable-getter: false
